### ISSUE TITLE
Support Jupyter notebooks again

### ISSUE THREAD

**Issue by daslu** [scicloj/tutorials#2]
We'll probably wait for this pull request to be merged:
https://github.com/clojupyter/clojupyter/pull/79

**Comment by behrica** [comment]
Whoosh ! 
This change of clojupyter could make it far more interesting to me.
To be able to connect the clojupyter notebook and an editor (just as Emacs) to the same nrepl instance
would allow me to "write complex parts of the code in Emacs" and use the notebook as the "rendering interface", just containing a minimum of code.

Gorilla-repl supported this way of working always.

Looking forward to see this PR merged.

**Comment by Dwaynekj** [comment]
Looks like it was merged!

**Comment by daslu** [comment]
Thanks, @Dwaynekj , we will start using it soon!

**Comment by daslu** [comment]
Updated the README and put the Jupyter example back.
